### ISSUE TITLE
Overlapped: init, eos token

### ISSUE THREAD

**Issue by huni1023** [enkeejunior1/study_NLP#2]
[(ipynb)](https://github.com/enkeejunior1/study_NLP/tree/main/assignment/Assignment4)

I can't understand the way tokenize

you first insert & append \<sos> & \<eos>,
and then insert again defining data.Field

`for idx, _ in tqdm(enumerate(en)):
    t = Tree.fromstring(en[idx])
    processed_token_list = [str.lower(token) for token in t.leaves()]
    
    processed_token_list.insert(0, '<sos>')
    processed_token_list.append('<eos>')
    `

````
KOREAN = data.Field( 
    init_token = '<sos>', 
    eos_token = '<eos>', 
    include_lengths = True
)

ENGLISH = data.Field( 
    init_token = '<sos>', 
    eos_token = '<eos>')
```

@

**Comment by huni1023** [comment]
I solve..

**Comment by enkeejunior1** [comment]
Thanks for a lot...
